name: Switch Node version
on:
  pull_request:

jobs:
  run-npm-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v3
        env:
          NODE_VERSION: 14
        with:
          node-version: ${{env.NODE_VERSION}}

      - name: run test
        run: |
          npm install
          npm test

      - name: node version
        run: node -v
