name: reusable workflow
on:
  workflow_dispatch:

jobs:
  run-npm-test:
    uses: justin-lonestone/github-actions-formation/.github/workflows/reusable-workflow.yaml@main
    with:
      node_version: 16
